//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstHomeWork.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class vw_CustomerDetailsCount
    {
        [Display(Name = "客戶ID")]
        public int CustomerID { get; set; }
        [Display(Name = "客戶名稱")]
        public string Customer { get; set; }
        [Display(Name = "帳號總數")]
        public Nullable<int> CountAccount { get; set; }
        [Display(Name = "聯絡人總數")]
        public Nullable<int> CountContact { get; set; }
    }
}
